#-------------------------------------------------------------------------
# TITLE: 
#    pkgIndex.tcl
#
# PROJECT:
#    notebook: Notebook Personal Wiki
#
# DESCRIPTION:
#    notebook quillinfo(n): pkgIndex file
#
#    Generated by Quill
#
#-------------------------------------------------------------------------

package ifneeded quillinfo 1.0 [list source [file join $dir pkgModules.tcl]]
