#-------------------------------------------------------------------------
# TITLE: 
#    pkgModules.tcl
#
# PROJECT:
#    notebook: Notebook Personal Wiki
#
# DESCRIPTION:
#    notebook: quillinfo(n) Package Loader
#
#    Generated by Quill
#
#-----------------------------------------------------------------------

package provide quillinfo 1.0

#-----------------------------------------------------------------------
# Get the library directory

namespace eval ::quillinfo:: {
    variable library [file dirname [info script]]
}

source [file join $::quillinfo::library quillinfo.tcl]
