#-------------------------------------------------------------------------
# TITLE: 
#    pkgModules.tcl
#
# PROJECT:
#    notebook: Your project description
#
# DESCRIPTION:
#    notebookapp(n): Package Loader
#
#    Generated by Quill
#
#-------------------------------------------------------------------------

#-------------------------------------------------------------------------
# Provide Package

# -quill-provide-begin DO NOT EDIT BY HAND
package provide notebookapp 2.2.0
# -quill-provide-end

#-------------------------------------------------------------------------
# Require Packages

# -quill-require-begin INSERT PACKAGE REQUIRES HERE
# -quill-require-end

#-------------------------------------------------------------------------
# Get the library directory

namespace eval ::notebookapp:: {
    variable library [file dirname [info script]]
}

source [file join $::notebookapp::library main.tcl]
