#-----------------------------------------------------------------------
# TITLE:
#	Makefile
#
# AUTHOR:
#	Will Duquette
#
# DESCRIPTION:
#	Tests the package.

TCLSH = tclsh
TESTFILE = notebookdb.test

all:
	$(TCLSH) $(TESTFILE) -verbose psb


