#-------------------------------------------------------------------------
# TITLE: 
#    pkgIndex.tcl
#
# PROJECT:
#    notebook: Notebook Personal Wiki
#
# DESCRIPTION:
#    notebookdb(n): pkgIndex file
#
#    Generated by Quill
#
#-------------------------------------------------------------------------

# -quill-ifneeded-begin DO NOT EDIT BY HAND
package ifneeded notebookdb 2.2.0 [list source [file join $dir pkgModules.tcl]]
# -quill-ifneeded-end
