#-------------------------------------------------------------------------
# TITLE: 
#    pkgIndex.tcl
#
# PROJECT:
#    notebook: Your project description
#
# DESCRIPTION:
#    app_notebook(n): pkgIndex file
#
#    Generated by Quill
#
#-------------------------------------------------------------------------

# -quill-ifneeded-begin DO NOT EDIT BY HAND
package ifneeded app_notebook 2.2.0 [list source [file join $dir pkgModules.tcl]]
# -quill-ifneeded-end
