#-------------------------------------------------------------------------
# TITLE: 
#    pkgModules.tcl
#
# PROJECT:
#    notebook: Your project description
#
# DESCRIPTION:
#    app_notebook(n): Package Loader
#
#    Generated by Quill
#
#-------------------------------------------------------------------------

#-------------------------------------------------------------------------
# Provide Package

# -quill-provide-begin DO NOT EDIT BY HAND
package provide app_notebook 2.2.0
# -quill-provide-end

#-------------------------------------------------------------------------
# Require Packages

# -quill-require-begin INSERT PACKAGE REQUIRES HERE
package require snit 2.3
# -quill-require-end

#-------------------------------------------------------------------------
# Get the library directory

namespace eval ::app_notebook:: {
    variable library [file dirname [info script]]
}

source [file join $::app_notebook::library main.tcl]
