#-------------------------------------------------------------------------
# TITLE: 
#    pkgModules.tcl
#
# PROJECT:
#    notebook: Notebook Personal Wiki
#
# DESCRIPTION:
#    markupparser(n): Package Loader
#
#    Generated by Quill
#
#-------------------------------------------------------------------------

#-------------------------------------------------------------------------
# Provide Package

# -quill-provide-begin DO NOT EDIT BY HAND
package provide markupparser 2.2.0
# -quill-provide-end

#-------------------------------------------------------------------------
# Require Packages

# -quill-require-begin INSERT PACKAGE REQUIRES HERE
package require textutil::adjust 0.7.1
# -quill-require-end

#-------------------------------------------------------------------------
# Get the library directory

namespace eval ::markupparser:: {
    variable library [file dirname [info script]]
}

source [file join $::markupparser::library markupparser.tcl]
